version: 2

updates:
  - package-ecosystem: npm
    schedule:
      interval: "daily"
    directory:
      path: "/"

  - package-ecosystem: npm
    schedule:
      interval: "daily"
    directory:
      path: "docs/"
